version: '3.8'
services:
  backend:
    build: ./backend
    ports: ['4000:4000']
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports: ['5173:80']
    environment:
      - VITE_WS_URL=ws://host.docker.internal:4000/ws
    depends_on:
      - backend
